### ISSUE TITLE
[ENH]: Add to conda-forge

### ISSUE THREAD

**Issue by pgbarletta** [Valdes-Tresanco-MS/gmx_MMPBSA#362]
### In which tool?

gmx_MMPBSA

### New Feature

My protocol dependes on gmx_mmpbsa and I'm trying to make it conda installable, and by now gmx_mmpbsa is the missing dependency.

### Description

Creating a `meta.yaml` and adding it to the staged-recipes of conda-forge.

### Relevance

medium

### Difficulty to implement

None

**Comment by Valdes-Tresanco-MS** [comment]
Oh sorry... I really didn't notice this issue. Currently, gmx_MMPBSA is in conda-forge (https://anaconda.org/conda-forge/gmx_mmpbsa). Unfortunately, the latest versions have been released unexpectedly, and we have not updated the package in conda (I will try to update it on Monday). However, just because it's not up to date in conda doesn't mean you can't use it as a dependency in conda. Conda accepts dependencies from PyPI unless you want to make a derivative of gmx_MMPBSA and depend exclusively on it to compile into the conda package. Take a look at this example:
```yaml
name: "gmx_MMPBSA"
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - ambertools=21.12
  - mpi4py=3.1.3
  - compilers=1.2.0
  - gromacs==2022.4
  - git
  - pip
  - pip: 
    - pyqt5==5.15.6
    - gmx-mmpbsa
    - git+https://github.com/Valdes-Tresanco-MS/ParmEd.git@v3.4
    - pandas==1.2.2
    - seaborn<0.12
    - scipy>=1.6.1
    - matplotlib>=3.5.1
    - tqdm
```
